services:
  php:
    container_name: OmniPlan-PHP
    build:
      context: .
    volumes:
      - ./:/srv/app/
    depends_on:
      - database
    environment:
      TZ: Europe/Bucharest
    restart: unless-stopped
    expose:
      - "9000"
    networks:
      - private
      - intern

  nginx:
    image: nginx:latest
    container_name: OmniPlan-NGINX
    ports:
      - "8181:80"
    volumes:
      - .:/srv/app/
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - public
      - private

  database:
    image: postgres:latest
    container_name: OmniPlan-DB
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    networks:
      - intern

networks:
  public:
  private:
  intern:

volumes:
  postgres_data:

